""":messge

Revision ID: f1b97c906905
Revises: 
Create Date: 2018-09-23 11:07:25.438546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b97c906905'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('author', sa.Column('password', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'author', ['password'])
    op.create_unique_constraint(None, 'author', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author', type_='unique')
    op.drop_constraint(None, 'author', type_='unique')
    op.drop_column('author', 'password')
    op.drop_column('author', 'email')
    # ### end Alembic commands ###
